### ISSUE TITLE
[Branch] dev branch 생성

### ISSUE THREAD

**Issue by stbaker517** [SKKU-2022F-OSSP-TEAM19/GitRank#10]
1. dev브랜치 만들었습니다 이 브랜치는 프론트 + 백엔드를 합쳐 마지막 최종 테스트를 하는 곳입니다.
2.  dev브랜치에 커밋 및 푸쉬하실 때는 꼭 자신이 맡은 파트만을 푸쉬해주세요

**Comment by Nainho** [comment]
dev 완성하였습니다.
