### ISSUE TITLE
edit 해결

### ISSUE THREAD

**Issue by Nainho** [SKKU-2022F-OSSP-TEAM19/GitRank#12]
제가 backend에서 app.js와 index.js도 어느정도 건드린 상태입니다.
다만, edit은 무엇이 문제인지 잘 모르겠네요.
같은 post 방식인 회원가입도 정상적으로 진행되고 있고,
edit.html에서 GET으로 정보는 잘 받아오고 있습니다.
insomnia로도 edit하는 방법은 잘 모르겠네요. 도움 부탁드립니다.
현재 backfront branch에 최종 결과물이 올라가 있는 상태입니다.

**Comment by Nainho** [comment]
실험을 해보신다고 하면, 먼저 GitRank/backend/gitrank에 가신 다음. npm start로 서버를 엽니다.
그 다음, localhost에서 열기 위해, cmd를 열어 GitRank로 갑니다. 거기서 http-server으로 localhost로 폴더를 열 수 있습니다.
이제 에러가 발생한다면, 그를 해결하기 위해 Access를 열어줘야 합니다.
저는 크롬을 주로 사용하였기에 크롬에서 플러그인을 설치해 주었습니다.
Allow CORS라는 플러그인인데, 설치하신 다음 크롬에서 프로필 사진이 있는 오른쪽 위에를 보시면 퍼즐 모양이 있습니다.
퍼즐이 플러그인을 관리하는 버튼이며, 클릭하시면 설치된 Allow CORS를 보실 수 있습니다.
클릭하시면 왼쪽 도형은 작동 여부를 클릭으로 제어하실 수 있으며, 색이 있는 상태가 켜진 상태입니다.
플러그인을 키시고, Open options page를 들어가 보시면 옵션을 설정할 수 있습니다.
3.Access-Control-Allow-Headers 를 체크해 주시고,
5.Access-Control-Allow-Origin은 *를 선택해주시면 됩니다.
밑에 Add a rule을 누르면 환경은 세팅된 것으로 생각됩니다.
이제, localhost:8080(default port입니다. http-server -p 3001 처럼 포트도 설정 가능합니다.)에 가시면 폴더들이 펼쳐집니다.
폴더에 들어가시고 .html을 누르면 페이지가 나옵니다. 이제 기능을 테스트 해보시면 됩니다.

**Comment by Nainho** [comment]
크롬 플러그인을 설치하면, http-server는 작동 하지 않아도 실행 되는 것 확인했습니다.
플러그인 설치하셔서, Access-Control-Allow-Origin 설정만 해주시면, 폴더에서 .html 접속하여도 됩니다.

**Comment by stbaker517** [comment]
코드 수정하여 업로드 하였습니다.

url 과 파라메터 구성은 기존과 동일하게 쓰시면 됩니다.

예시

**POST**
http://localhost:3000/userpage/edit/nickel

{
	"ID":"nickel",
	"IMG":"photo src",
  "INTERESTS":["BACKEND","FRONTEND","DATA","DB"],
  "COMMENT":"testestes",

  "SKILLS":["C++","PYTHON","JAVA","LOL","LOL"]
}



**OUTPUT**
{
	"profile": {
		"ID": "nickel",
		"GITHUB": "stbaker517",
		"IMG": "photo src",
		"INTERESTS": [
			"BACKEND",
			"FRONTEND",
			"DATA",
			"DB"
		],
		"COMMENT": "testestes",
		"SCORE": 0,
		"SKILLS": [
			"C++",
			"PYTHON",
			"JAVA",
			"LOL",
			"LOL"
		]
	}
}

**Comment by Nainho** [comment]
해결 되었습니다.
