### ISSUE TITLE
edit 추가

### ISSUE THREAD

**Issue by Nainho** [SKKU-2022F-OSSP-TEAM19/GitRank#18]
점수를 수정할 수 있는 공간을 만든다.
점수에 따라 등급을 나눠서 프로필에서 보여준다.
또한, 설정한 점수에 따라 rank에서 순위가 결정된다.

회원가입처럼 체크박스를 만들어준다.
이미 선택한 것은 체크된 채로 보여주고, 체크된 분야로 Interests와 Skills를 수정한다.

또한, 컨택을 hyperlink로 표현하여 누를 시 바로 메일 작성으로 넘어가게 한다.

**Comment by Nainho** [comment]
@GeonhanKang profile.html, myprofile.html, edit.html도 기존 창처럼 정리해주시면 됩니다.
edit의 경우, 회원가입에서 한 것처럼, Interests, Skills 모음을 만들어주시면 됩니다.
profile, myprofile에는 Interests 밑에 skills를 추가해주시면 됩니다.

완성이 되면, 제가 js로 내부 함수 완성하도록 하겠습니다.

점수관련은 이 기능이 완성이 되면 생각해보도록 하겠습니다.
현재 진행된 최종본은 backfront에 있습니다.

**Comment by GeonhanKang** [comment]
@Nainho 기존 창처럼 정리한다는 것이 html디자인을 다시 만들어 오라는 말씀이신가요?

**Comment by Nainho** [comment]
@GeonhanKang 넵. 기존 rank, signin, signup 만드신 것처럼 정리해주시면 됩니다.

**Comment by Nainho** [comment]
서버와 연결이 힘드시면, 기존 local strage로 보시면서 디자인 완성하시면 될 것 같습니다

**Comment by Nainho** [comment]
기능 구현 완료하였습니다.
