### ISSUE TITLE
Notion API sheet 추가 완료

### ISSUE THREAD

**Issue by stbaker517** [SKKU-2022F-OSSP-TEAM19/GitRank#19]
프로젝트 초기 단계에서 구상했던 모든 api의 제작을 완료하였으며

api에 대한 정보를 notion에 정리해두었습니다.

문의 있으시면 comment 남겨주세요

@Nainho @GeonhanKang

**Comment by Nainho** [comment]
backend에서 index.js, app.js 수정된 사항이 있으니 향후 참고 바랍니다.

rank에서 정보를 가져올 때는 DB_users에서 가져오지만, 수정을 할 때는 DB_profile만을 수정하도록 되어 있었습니다.
수정된 사항을 반영하기 위해 모든 함수에서 DB_users만을 사용하도록 수정하였습니다.
덧붙여, app.js에서도 추가된 기능이 몇 있습니다.
edit에서 사진을 교환할 때, 크기에 제한이 걸리기에 제한을 풀어주는 함수 등이 추가된 상태입니다.

**Comment by Nainho** [comment]
프론트도 초기에 구상했던 모든 기능 완료하였습니다.
