### ISSUE TITLE
회원가입 페이지 feature 추가 요청

### ISSUE THREAD

**Issue by stbaker517** [SKKU-2022F-OSSP-TEAM19/GitRank#2]
회원가입 페이지에서 ID,PASSWORD, GITHUB, INTERESTS 정보만을 받고 있습니다.

하지만 우리가 구현하려는 대로 하려면 회원가입에서 SKILL에 대한 information을 받아올 필요가 있습니다.

따라서  INTEREST와 같이 SKILL 정보도 INPUT form을 만들어야합니다.

**Comment by Nainho** [comment]
skill이 Program Languages를 의미하는 것이죠?
그렇다면, 라디오 박스나, 체크박스를 통해 구현하는 것이 좋을까요?
아니면, 기존과 똑같이 textbox를 사용할까요?

**Comment by stbaker517** [comment]
@Nainho 

https://getbootstrap.com/docs/5.0/forms/checks-radios/
에서 우측 리스트 보시면 Outlined styles가 있습니다.

해당 기능 이용하면 어떨까 싶습니다.

**Comment by stbaker517** [comment]
해당 기능 테스트 후 회원가입 페이지에 적용 하시면 this issue close 해주시면 될 것 같습니다.

**Comment by Nainho** [comment]
체크박스 사용해서 구현하였습니다.
