### ISSUE TITLE
git score 함수 변경 완료

### ISSUE THREAD

**Issue by stbaker517** [SKKU-2022F-OSSP-TEAM19/GitRank#32]
git api가 아닌 http로 받아옵니다.

무한 refrech해도 괜찮습니다.

api에 변동은 없으니 프론트에서 따로 수정할 필요는 없습니다.

@Nainho @GeonhanKang

**Comment by stbaker517** [comment]
재수정했습니다.

**Comment by Nainho** [comment]
수정된 버전으로 테스트 해보니 500점으로 출력합니다.
