### ISSUE TITLE
GitHub score 함수 업데이트 및 마이 페이지 깃허브 그래프 관련 코드.

### ISSUE THREAD

**Issue by stbaker517** [SKKU-2022F-OSSP-TEAM19/GitRank#36]
1. Github score함수를 계산하기 위해 직접 github 레포를 파싱하는 방식으로 바꿨습니다. 기존보다 안전하며 터지지 않을 겁니다.

2. 깃 커밋 그래프의 코드를 구해왔습니다. https://coding-groot.tistory.com/109의 html코드를 그대로 쓰면 됩니다. 단, 22번째 줄에 있는 I am groot 파라메터를 깃헙id로 바꿔야합니다. 아래 코드가 예시입니다.
` GitHubCalendar(".calendar", "IamGroooooot" ( <-  여기에 깃헙 아이디를 넣어야합니다.)  , { responsive: true, tooltips: false, global_stats: false}).then(function() {`

**Comment by Nainho** [comment]
@stbaker517 
기존 방식이 복구 되었습니다.
새로운 방식 작업이 필요할까요?
