### ISSUE TITLE
백엔드 작업 완료 및 프론트에서 fetch 시험 필요

### ISSUE THREAD

**Issue by stbaker517** [SKKU-2022F-OSSP-TEAM19/GitRank#7]
2022-11-23 목요일 처음 의도했던 백엔드 작업 완전 완료 했습니다.

프론트에서 fetch해서 테스팅 해주시고

작업 진행 상황 코멘트 부탁드립니다.

@Nainho @GeonhanKang

**Comment by Nainho** [comment]
signup에서 fetch해서 POST 방식으로 정보 보내기 성공하였고,
rank에서 GET 방식으로 가져오기 성공했습니다.

**Comment by stbaker517** [comment]
@Nainho 고생하셨습니다. 
모든 기능은 구현되었으나 api sheet를 작성하지 않은 부분이 있습니다.
나머지 api sheet 작업하여 노션에 업로드 하겠습니다.

**Comment by Nainho** [comment]
edit 기능을 제외하면 모두 완료하였기에 이 이슈는 닫고 edit만 다루는 다른 이슈를 만들겠습니다.
